const cards = [
	{
		id: 1,
		model: "Volvo",
		stateNumber: "C772MK34",
		tracker: "GPS",
		group: "Автоцистерна",
		driver: "Сергей Иванов",
		phone: "(929) 777-55-77",
		startCountry: "Россия",
		endCountry: "Россия",
		startPoint: "Москва",
		endPoint: "Волгоград",
		status: "В пути",
		startCoord: [55.75, 37.61],
		endCoord: [48.43, 44.30],
		distance: 996,
		speed: 86,
		doneDistance: 312,
		fullDistanceTime: "11 ч 4 мин",
		restDistanceTime: "6 ч 13 мин",
		readyRoute: true,
		tiltAngle: false,
		wrongRoute: false,
		photo: "../sources/assets/photo/volvo.jpg"
	},
	{
		id: 2,
		model: "Scania",
		stateNumber: "C481MK78",
		tracker: "Глонасс",
		driver: "Андрей Давыдов",
		phone: "(929) 109-675-1",
		startCountry: "Беларусь",
		endCountry: "Россия",
		startPoint: "Минск",
		endPoint: "Москва",
		group: "Фургон",
		status: "В пути",
		startCoord: [53.90, 27.56],
		endCoord: [55.75, 37.61],
		distance: 716,
		speed: 98,
		doneDistance: 511,
		fullDistanceTime: "7 ч 58 мин",
		restDistanceTime: "3 ч 16 мин",
		readyRoute: true,
		tiltAngle: false,
		wrongRoute: true,
		photo: "../sources/assets/photo/scania.jpg"
	},
	{
		id: 3,
		model: "Man",
		stateNumber: "C478MK78",
		tracker: "GPS",
		driver: "Алексей Фролов",
		phone: "(929) 478-632-8",
		startCountry: "Россия",
		endCountry: "Россия",
		startPoint: "Москва",
		endPoint: "Смоленск",
		group: "Фургон",
		status: "В пути",
		startCoord: [55.75, 37.61],
		endCoord: [54.78, 32.04],
		distance: 399,
		speed: 90,
		doneDistance: 124,
		fullDistanceTime: "4 ч 26 мин",
		restDistanceTime: "3 ч 19 мин",
		readyRoute: true,
		tiltAngle: true,
		wrongRoute: false,
		photo: "../sources/assets/photo/man.jpg"
	},
	{
		id: 4,
		model: "Man",
		stateNumber: "C233MK34",
		tracker: "Глонасс",
		status: "Без маршрута",
		driver: "Константин Сидоров",
		phone: "(929) 498-012-3",
		group: "Рефрижератор",
		readyRoute: false,
		tiltAngle: false,
		wrongRoute: false,
		photo: "../sources/assets/photo/man.jpg"
	},
	{
		id: 5,
		model: "Scania",
		stateNumber: "C198MK34",
		tracker: "GPS",
		status: "Без маршрута",
		driver: "Максим Заславский",
		phone: "(929) 433-300-2",
		group: "Автоцистерна",
		readyRoute: false,
		tiltAngle: false,
		wrongRoute: false,
		photo: "../sources/assets/photo/scania.jpg"
	}
];

export default cards;
